stages:

- stage: test

  jobs:
  - job: macOS
    pool:
      vmImage: 'macOS 10.14'

    steps:
    # To manually select a Xamarin SDK version on the Hosted macOS agent, enable this script with the SDK version you want to target
    # https://go.microsoft.com/fwlink/?linkid=871629
    - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_8_0_0
      displayName: Select Xamarin SDK version
      enabled: false

    - script: |
        SYMLINK=5_18_1
        MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
        echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
        echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
        echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
      displayName: Select MONO version

    - bash: make restore
      displayName: Restore nuget packages

    - bash: make test
      displayName: Run tests

- stage: build
  dependsOn:
  - test

  jobs:
  - job: macOS
    pool:
      vmImage: 'macOS 10.14'

    steps:
    - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_8_0_0
      displayName: Select Xamarin SDK version
      enabled: false

    - script: |
        SYMLINK=5_18_1
        MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
        echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
        echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
        echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
      displayName: Select MONO version

    - bash: make
      displayName: Build macos application
